module.exports = {
  appId: 'PASTE_PUSHER_CHANNELS_APPID',
  key: 'PASTE_PUSHER_CHANNELS_KEY',
  secret: 'PASTE_PUSHER_CHANNELS_SECRET',
  cluster: 'PASTE_PUSHER_CHANNELS_CLUSTER',
  secretKey: 'PASTE_PUSHER_BEAMS_SECRET',
  instanceId: 'PASTE_PUSHER_BEAMS_INSTANCEID'
};
